FROM postgres:14-bullseye
ENTRYPOINT ["/run.sh"]
CMD ["postgres"]
RUN apt-get update && \
apt install -y postgresql-server-dev-14 python-dev build-essential git python3-pip procps sockstat


ADD config* /
ADD run.sh /run.sh
COPY init/* /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
    chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh
